# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestlogin():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testlogin(self):
    self.driver.get("http://localhost/")
    self.driver.set_window_size(816, 705)
    self.driver.find_element(By.LINK_TEXT, "登录").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("15800000001")
    self.driver.find_element(By.ID, "password").send_keys("123456")
    self.driver.find_element(By.CSS_SELECTOR, ".sum_reme_for").click()
    self.driver.find_element(By.ID, "verify_code").click()
    self.driver.find_element(By.ID, "verify_code").send_keys("8888")
    self.driver.find_element(By.LINK_TEXT, "登    录").click()
    self.driver.close()
  
